// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjn073PaMa6--Of-MUmrTOiMS0EYfpU_Y',
    appId: '1:942358029028:web:644f0aee6a09deba4e82f1',
    messagingSenderId: '942358029028',
    projectId: 'splitkarona',
    authDomain: 'splitkarona.firebaseapp.com',
    storageBucket: 'splitkarona.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PGUvEikzoIAdmnlSpqklVdoxtiB175I',
    appId: '1:942358029028:android:30673c8a982559aa4e82f1',
    messagingSenderId: '942358029028',
    projectId: 'splitkarona',
    storageBucket: 'splitkarona.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05OB_RW0FxjcODqPyLSK9v_kIdAHMTPA',
    appId: '1:942358029028:ios:d53ff45a902cba994e82f1',
    messagingSenderId: '942358029028',
    projectId: 'splitkarona',
    storageBucket: 'splitkarona.firebasestorage.app',
    iosBundleId: 'com.splitkarona.splitkaroNa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05OB_RW0FxjcODqPyLSK9v_kIdAHMTPA',
    appId: '1:942358029028:ios:d53ff45a902cba994e82f1',
    messagingSenderId: '942358029028',
    projectId: 'splitkarona',
    storageBucket: 'splitkarona.firebasestorage.app',
    iosBundleId: 'com.splitkarona.splitkaroNa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjn073PaMa6--Of-MUmrTOiMS0EYfpU_Y',
    appId: '1:942358029028:web:57f4511df34da3294e82f1',
    messagingSenderId: '942358029028',
    projectId: 'splitkarona',
    authDomain: 'splitkarona.firebaseapp.com',
    storageBucket: 'splitkarona.firebasestorage.app',
  );
}
